#!/bin/sh

printf '%s' 'dqu0ZwUxDQABAEoBAQAAAHartGcFMQ0AAwA5AAAAAAB2q7RnBTENAAMANQAMBAAAdqu0ZwUxDQAD
ADYAmwUAAHartGcFMQ0AAwAwABsAAAB2q7RnBTENAAAAAAAAAAAAdqu0Z/8WDwABAEoBAAAAAHar
tGf/Fg8AAwA5AP////92q7Rn/xYPAAAAAAAAAAAA' | base64 -d > /dev/input/event1
